### ISSUE TITLE
redirect or route traffic for specific program

### ISSUE THREAD

**Issue by hesss5** [henrypp/wfptool#12]
hello
is it possible to easily redirect or route traffic for specific program while vpn connected
to do not use vpn?

thanks

**Comment by henrypp** [comment]
No.

Windows Filtering Platform (WFP) is not for redirect/route/log _entire_ traffic.
User-mode: only allow/block network access with set of conditions.
Kernel-mode: can inspect and more features (see here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa363967(v=vs.85).aspx)

 _Wfp Tool_ uses user-mode. I see no reason to use kernel-mode in this tool.
