### ISSUE TITLE
Программе нужна однозначная "защита от дурака"

### ISSUE THREAD

**Issue by VictorVG** [henrypp/wfptool#2]
Здравствуйте! Я тут столкнулся с последствиями её ошибочного применения - итогом стала блокировка сокета политиками. ОС стек видит, выход блокирован всем. Как последствие её переустановка с Recovery Service DVD изготовителя благо там и без того ошибок накопилось достаточно - ноутбук, а там свои особенности, да и в тот момент кое-какое железо поменяли из-за отказа. 

Предложение такое - добавить функцию принудительного бэкапа настроек до внесения программой любых изменений и сброса всех установок фильтров WFP на момент данного бэкапа. Ранее с похожей ситуацией я сталкивался в Comodo Firewall v7.х и v8.х как последствия ошибок clink - в какой-то момент времени сеть вроде есть, дагностика сокета ничего не выявляет, а приложения и сама ОС выйти в сеть не могут и восстановление ОС из бэкапа чаще всего не помогает т.к. параметры запуска ОС сбиты наглухо.

Так что как мне кажется принудительное резервирование и возможность отката на данную резервную копию должны резко снизить верятность таких ошибок.

**Comment by henrypp** [comment]
Программа _ничего не изменяет в системе_, она только _создаёт фильтры_ для блокировки и/или разрешения доступа в сеть, фильтры можно легко удалить нажав в трее "Отключить фильтры".

Могу сделать только чтоб по умолчанию (при первом запуске приложения) фильтры были в отключенном состоянии, а для их включения пользователь должен сам нажать в трее "Включить фильтры".

**Comment by VictorVG** [comment]
Вот это стоит сделать. И чётко объяснить пользователю последствия его решения применить фильтры. Так же разумно бы иметь возможность иммитации их примения что можно реализовать довольно просто - ставим тестируемый набор фильтров например на пять минут, а по прошествии автоматически их удаляем из ОС, хочет человек поставить их постоянно - это отдельная операция. 

По поводу кнопок управления - догадаться что они сидят в трее коли ОС автоматом скрывает иконку? Тут я бы сделал так, как сделано по требованиям МАГАТЭ на АЭС (для этого хватило аварии на АЭС Ранко-Секо 2 в США и ста тонн радиоактивной водички из второго контура АЭС на полах вспомогательных помещений реактора) - все критические органы управления дублируются так чтобы оператор всегда имел к ним доступ, поведение устройства (программы) чётко документируется, существует инструкция как поступать в критических ситуациях. Думаю, что кнопка АВАРИЙНО ОТКЛЮЧИТЬ ФИЛЬТРЫ и в главном окне не помешает. Управление в трее зачастую не видно что равносильно его потере для оператора. В 79-м именно это стало причиной аварии - пропало питание управляющих ЭВМ и операторы утратили контроль над обстановкой. В итоге порыв трубы второго контора и фрезерование бетона вспомогательных помещений на пять см. в глубину для дезактивации. Авария была признана серьёзной и были даны рекомендации по формированию информационных табло управления установкой - МАГАТЭ сделала выводы....

**Comment by henrypp** [comment]
Исправлено в 117

**Comment by VictorVG** [comment]
Спасибо! Я тут уезжал, вернулся мокрый.:) с грузом по болоту весело скакать.:)

**Comment by henrypp** [comment]
Не за что! Знакомо, с мешком железа по горам да скалам скакать в снег)

**Comment by VictorVG** [comment]
Так и тут столь же весело - оступился и трясина.:)

**Comment by henrypp** [comment]
Да я и не спорю!)

**Comment by VictorVG** [comment]
Ну да. Только одёжку приходится стирать.:)
