### ISSUE TITLE
No Filtering of System32, SysWOW64 and Startup Processes

### ISSUE THREAD

**Issue by HJLBX** [henrypp/wfptool#4]
System32, SysWOW64 and Startup processes are default-allow in Wfp Tool.

Adding System32, SysWOW64 and Startup processes to the filter list (using Add Process) does not generate any alerts.

For example, add ping.exe and execute it (cmd > ping github.com) generates no alerts form Wfp Tool.

Malware often abuses System32, SysWOW64 processes and\or will insert itself to auto-run at Windows startup.

**Comment by henrypp** [comment]
check settings for "svchost.exe" & "system" it excluded from log by default in 1.3.1

**Comment by HJLBX** [comment]
Here is MEGA video download link:  [https://mega.nz/#!ZAJVULTT!nwLQQtWPAcEFICfCnxR2FaCQS4zML9O-JgCY7So7H2o](url)

Find HTML5 folder > demo.html > right-click > Open with Google Chrome (use Chrome for best video quality)

**Comment by HJLBX** [comment]
LOL... for whatever reason GitHub does not open MEGA link, but instead re-directs to 404.

Not making it easy for us...

To access MEGA:

1.  Highlight URL with cursor (blue color)
2.  Right-click
3.  Copy
4.  Open new tab in browser
5.  Paste URL

**Comment by HJLBX** [comment]
[http://www57.zippyshare.com/v/zJBTpSbf/file.html](url)
