### ISSUE TITLE
Upon Installation, Wfp Tool Continues to Generate Alerts After a Process Has Been Allowed

### ISSUE THREAD

**Issue by HJLBX** [henrypp/wfptool#5]
Install Wfp Tool and filtering

Wfp Tool will generate alerts for System, dnscrypt, Google, etc

After allowing the above processes within Wfp Tool, it will continue to generate outbound connection alerts.

NOTE:  Also, you will notice that running ping.exe generates no Wfp Tool alert.

To watch video:

HTML5 folder > demo.html > right-click > Open with Google Chrome

[Wfp Tool.zip](https://github.com/henrypp/wfptool/files/560548/Wfp.Tool.zip)

**Comment by henrypp** [comment]
after add application to list you need to check it to allow ;)

**Comment by HJLBX** [comment]
Here is MEGA download link of complete video:  [https://mega.nz/#!sB5nzIRQ!la3xVMrWIB65EMXs39QDksRaABEPExgxEtoPkBAY1ow](url)

**Comment by henrypp** [comment]
i cant open mega.nz

**Comment by HJLBX** [comment]
LOL... for whatever reason GitHub does not open MEGA link, but instead re-directs to 404.

Not making it easy for us...

To access MEGA:

Highlight URL with cursor (blue color)
Right-click
Copy
Open new tab in browser
Paste URL

**Comment by HJLBX** [comment]
[http://www57.zippyshare.com/v/wk2yAHYs/file.html](url)
