### ISSUE TITLE
PPTP

### ISSUE THREAD

**Issue by gameb0y** [henrypp/wfptool#6]
Can't connect to PPTP server behind wfptool

**Comment by jasonliul** [comment]
Add port 1723, setting permit.

**Comment by heforfree** [comment]
hi
maybe you can add bellow example to rules->port on top of custom rule in setting with description
it will make handy and fast to enable which one user want
https://msdn.microsoft.com/en-us/library/cc875824.aspx
or
http://whatismyipaddress.com/port-list

**Comment by henrypp** [comment]
@heforfree nice idea!
