### ISSUE TITLE
added process will be cleared

### ISSUE THREAD

**Issue by heforfree** [henrypp/wfptool#7]
hello
thanks for update
run portable version
right click on main window add process > all
then i select program that i want allow,then from file menu select setting
now i check and unch some options after click apply or close
all process added by "add process > all" will disappear include white listed program 
this happen with or without installed filter

**Comment by henrypp** [comment]
i'm try to find and fix.
if it happens (listview clearing) try to push "Refresh... F5" button

**Comment by heforfree** [comment]
Refresh... F5 don't revert back them

**Comment by hesss5** [comment]
same here f5 will also remove list

**Comment by henrypp** [comment]
@heforfree 
@hesss5 
try 1.3.4, it's bug in xml saving, i'mrevert old xml parsing library version and i think it fixed, check please!

**Comment by hesss5** [comment]
hello
still it will lost from list and should recreate rules

**Comment by heforfree** [comment]
hi
same problem.even when refresh list will be cleared

**Comment by hesss5** [comment]
ok i look in to v1.3.2 and found after adding process file config.xml will be created but
in new version don't
so that's should the problem as you mention that

**Comment by henrypp** [comment]
1.3.5 fixed
